name: Docker Image CI

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Build the Docker image
        run: docker build ./randomquotes --file ./randomquotes/Dockerfile --tag drew138/express-randomquotes:latest
      - name: Docker Push
        run: docker push drew138/express-randomquote
